version: "3.8"
services:
    db:
        image: mysql
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: mabdon
            MYSQL_USER: 'mabdon'
            MYSQL_PASSWORD: 'tMujscZc8ywPgDMT4Y'
            MYSQL_ROOT_PASSWORD: 'tMujscZc8ywPgDMT4Y '
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        networks:
            - default
    www:
        build: 
          context: '.'
          args:
            uid: 1000
        ports: 
            - "80:80"
        volumes:
            - ./www:/var/www/html
        links:
            - db
        networks:
            - default
volumes:
    persistent:
